updates_to_mips_subroutine

diff --git a/bin/mips_subroutine b/bin/mips_subroutine
--- a/bin/mips_subroutine
+++ b/bin/mips_subroutine
@@ -13,7 +13,7 @@ case ${0} in
 
      ;;
 
-   *java_subroutine)
+   *j*_subroutine)
      VERSION="java"
      LANG_EXT="j"
      DUMP_X_REGISTERS=""
@@ -245,6 +245,13 @@ function sub_routine_call () {
 ###########################################################################
 
 build_java_source () {
+  # build the class
+  # include all of the .j files
+  # include the entry .j files
+  # build the main subroutine
+  #   call the entry subroutine
+  # close the main subrouine
+  # close the class
 
 cat <<-EOF
 class ${SUB_NAME} {
@@ -288,17 +295,33 @@ EOF
          echo "         for (index=0; index < \$a$i.length - 2; index++ ) {"
          echo "           \$a$i[index] = (string_$i).charAt(index);"
          echo "         }"
+         echo "         \$a$i[index] = '\0' ; // the Null character"
          echo "         \$a$i[index+1] = '\7' ; // the Alert character"
          ;;
     esac
   done
 
 echo    ""
-echo -n "    int \$v0 = "     #modify this based upon return type
+
+# Call the subroutine, but first Marshal the args on the stack.
+
+num_a_regs=${#SUB_ARGS_TEXT[@]}
+if (( ${#SUB_ARGS_TEXT[@]} > 4)) ; then
+  num_a_regs=4
+fi
+
+# Marshal the stack arguments:
+for ((i=4; i < ${#SUB_ARGS_TEXT[@]}; i++)) ; do 
+  echo     "    mips.push(\$a$i);" 
+done
+
+  echo -n  "    int \$v0 = "     #modify this based upon return type
   echo -n "${SUB_NAME}("
-  for ((i=0; i < ${#SUB_ARGS_TEXT[@]}; i++)) ; do
+
+  # Marshal in Registers
+  for ((i=0; i < num_a_regs; i++)) ; do
     echo -n "\$a$i"
-    if (( i != ${#SUB_ARGS_TEXT[@]} -1 )) ; then
+    if (( i != num_a_regs -1 )) ; then
       echo -n ", "
     fi
   done
@@ -970,26 +993,26 @@ SUB_NAME=$(basename ${SUB_NAME})
 
 # Command line related error checking
 [ ${SUB_NAME} != "main" ] || 
-     { echo "File name cannot be \"main.${LANG_EXT}\"." ; exit 1; }
+     { echo "Error: File name cannot be \"main.${LANG_EXT}\"." ; exit 1; }
 
 [ -f ${SUB_NAME_FILE} ] || 
-     { echo "File \"${SUB_NAME_FILE}\" does not exist." ; exit 1 ; }
+     { echo "Error: File \"${SUB_NAME_FILE}\" does not exist." ; exit 1 ; }
 
 if [[ ${VERSION} == "mips" ]] ; then 
   grep -q "${SUB_NAME}:" ${SUB_NAME_FILE}  || 
-       { echo "Subroutine $SUB_NAME not defined" ; exit 1; }
+       { echo "Error: Subroutine $SUB_NAME not defined" ; exit 1; }
   grep -q "\.globl *${SUB_NAME}" ${SUB_NAME_FILE}  || 
-       { echo "Subroutine $SUB_NAME not defined .globl" ; exit 1; }
+       { echo "Warning: Subroutine $SUB_NAME not defined .globl" ; }
 fi
 
 if [[ ${VERSION} == "java" ]] ; then 
   grep -q "public  *static  *int  *${SUB_NAME} *(" ${SUB_NAME_FILE}  || 
-       { echo "Subroutine $SUB_NAME not declared \"public static int\"." ; exit 1; }
+       { echo "Error: Subroutine $SUB_NAME not declared \"public static int\"." ; exit 1; }
 fi
 
 if [[ ${VERSION} == "c" ]] ; then 
   grep -q "${SUB_NAME}:" ${SUB_NAME_FILE}  || 
-       { echo "Subroutine $SUB_NAME not defined." ; exit 1; }
+       { echo "Error: Subroutine $SUB_NAME not defined." ; exit 1; }
 fi
 
 
